### PR TITLE
fix: handle extensions like `page.tsx`

### LINKED ISSUE #319: Unexpected path name when using `page.tsx` as extension
### Describe the bug

I'm using this wonderful plugin for a React SPA, but I want my `pages/feature/` directory to contain feature specific components without turning every single one into a page.

So, I setup vite-plugin-pages with the following:

```
    Pages({
      dirs: [{ dir: "pages", baseRoute: "" }],
      extensions: ["page.tsx"],
    }),
```

It picks up the `feature/index.page.tsx` just fine. Except it doesn't strip the entire extension away from the path name. I'd expect path to be `feature`, but instead it's `feature.page`

In the StackBlitz, check the console for the app route line. It should match `index.page.tsx` (and it does), but the path name is incorrect `index.page`.

Is this intended behaviour, and if so; is there any of fulfilling my use-case of adding a postfix to the page routes, so that not all components are picked up by the plugin?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-b4bobc?file=vite.config.ts

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.29 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0.1
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A please open a GitHub Discussion.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by kota65535**
### Description

fixes #319 

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by kota65535** [comment]
Hmm, I have no idea why some workflows fail. Simply unstable for now?

**Comment by hannoeru** [comment]
@kota65535 Yes, e2e test are unstable now, just ignore it.

**Comment by kota65535** [comment]
@hannoeru
At first, I tried considering the rest of the string as the extension after the first dot, but then I realized that it cannot handle file names like `v1.2.pages.tsx` to be mapped to the path `/v1.2`.
So I think both of two options `filePattern` and `extensions` are needed to define the mapping from file names to paths correctly.
Any ideas to simplify it?

File: src/context.ts [hunk 1]
```diff
@@ -76,7 +76,8 @@ export class PageContext {
     debug.pages('add', path)
     for (const p of toArray(path)) {
       const pageDirPath = slash(resolve(this.root, pageDir.dir))
-      const route = slash(join(pageDir.baseRoute, p.replace(`${pageDirPath}/`, '').replace(extname(p), '')))
+      const extension = ensurePrefix('.', this.options.extensions.find(e => p.endsWith(e)) ?? extname(p))
```
Comment (hannoeru) [inline src/context.ts:79]: `extname()` will return extname with `.` prefix so we don't need to wrap it with `ensurePrefix`.

File: src/options.ts [hunk 2]
```diff
@@ -71,6 +71,8 @@ export function resolveOptions(userOptions: UserOptions, viteRoot?: string): Res
 
   const extensions = userOptions.extensions || resolver.resolveExtensions()
 
+  extensions.sort((a, b) => b.length - a.length)
```
[the remark this answers is not in the document]
Comment (kota65535) [reply src/options.ts:74]: Suppose the extensions option is set to `["tsx", "page.tsx"]`.
Because `find` function searches the array from the head, if there is a file `foo.page.tsx`, the first `tsx` matches and its path will be `foo.page`. But users generally expect to match with `page.tsx` and its path will be `foo`.

But yes, this is maybe a bit confusing feature. Instead, we should add documentation about the extension priority so that the users are aware of it.

File: src/context.ts (hunk 1 above)
Comment (kota65535) [reply src/context.ts:79]: Yes, at first I wrote the following but changed the code because `ensurePrefix` does no harm even if the prefix already exists.

```javascript
let extension = this.options.extensions.find(e => p.endsWith(e))
if (extension) {
  extension = ensurePrefix(".", extension)
} else {
  extension = extname(p)
}
```

In the first place, should we fallback to `extname` function when the file does not match any extension? When users specify `extensions` option explicitly, they do not expect files with any other extension to be converted to pages, do they?

Comment (hannoeru) [reply src/context.ts:79]: > In the first place, should we fallback to extname function when the file does not match any extension?

Yes, I think remove extname fallback make sense to me.

File: src/options.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (hannoeru) [reply src/options.ts:74]: > Sort by string length to find the longest extension later

So you mean to find the longest extension first.

> Because find function searches the array from the head, if there is a file foo.page.tsx, the first tsx matches and its path will be foo.page. But users generally expect to match with page.tsx and its path will be foo.

Got it. but still I think this is a little bit confused, so let's add some doucmentaiton about extension priority and remove this extension sort.

**Comment by kota65535** [comment]
@hannoeru  Fixed, please check.

File: src/context.ts [hunk 3]
```diff
@@ -76,7 +76,10 @@ export class PageContext {
     debug.pages('add', path)
     for (const p of toArray(path)) {
       const pageDirPath = slash(resolve(this.root, pageDir.dir))
-      const route = slash(join(pageDir.baseRoute, p.replace(`${pageDirPath}/`, '').replace(extname(p), '')))
+      const extension = this.options.extensions.find(e => p.endsWith(e))
+      if (!extension) continue
+
+      const route = slash(join(pageDir.baseRoute, p.replace(`${pageDirPath}/`, '').replace(extension, '')))
```
Comment (hannoeru) [inline src/context.ts:82]:
```suggestion
      const extension = this.options.extensions.find(ext => p.endsWith(`.${ext}`))
      if (!extension) continue

      const route = slash(join(pageDir.baseRoute, p.replace(`${pageDirPath}/`, '').replace(`.${extension}`, '')))
```

**Required**: we should remove extension including `.` from route path

Comment (kota65535) [reply src/context.ts:82]: Oh sorry, I didn't make sure to work properly after fixing it, thanks.

**Comment by kota65535** [comment]
@hannoeru Oh sorry, I didn't make sure to work properly after fixing it, thanks.
I've added the change you suggested.
